### ISSUE TITLE
Subdomains not working

### ISSUE THREAD

**Issue by Oreki-Dev** [Olivr/free-domain#259]
The recently registered subdomains are not pointing towards the records chosen, has this service closed down?

**Comment by Oreki-Dev** [comment]
@politician ^

**Comment by politician** [comment]
Hi @Oreki-Dev, thanks for pointing out. [There was a bug that has now been fixed](https://github.com/Olivr/free-domain/pull/269). It was preventing any modification to the wip.la/cluster.ws zones. This meant that any new subdomain added to this repo in the last month was not actually added in the zone file.

Now that this bug is fixed, all subdomains registered in the past month are now working.

cc @TerraPlayz @iisalazar @elchn @anjuucoklubis @coral-86-2 @koskrit @MicroBotCodes @zbtechph @tomenjerry @akeuk @imxarath @sxjeru @redwerkz @dhanushreddy291 @ssangyongsports @sxadxsx @UnFunnyGuy @LazyMaple @nischay876 @adehghanzadeh @AkumaX1 @marulitua
